name: Python3.9 - docker build and push images to dockerhub

on:
  push:
    branches:
      - 'main'

jobs:
  python39-slim:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      
      - name: Build python3.9-slim
        run: |
          docker build \
            -t naylscloud/python:3.9-slim \
            -f ./3.9/python3.9-slim.dockerfile \
            ./3.9
          docker push naylscloud/python:3.9-slim
    
  python39-slim-sdk:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Build python3.9-slim-sdk
        run: |
          docker build \
            -t naylscloud/python:3.9-slim-sdk \
            -f ./3.9/python3.9-slim-sdk.dockerfile \
            ./3.9
          docker push naylscloud/python:3.9-slim-sdk

  python39-slim-poetry:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Build python3.9-slim-poetry
        run: |
          docker build \
            -t naylscloud/python:3.9-slim-poetry \
            -f ./3.9/python3.9-slim-poetry.dockerfile \
            ./3.9
          docker push naylscloud/python:3.9-slim-poetry

  python39-slim-poetry-sdk:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Build python3.9-slim-poetry-sdk
        run: |
          docker build \
            -t naylscloud/python:3.9-slim-poetry-sdk \
            -f ./3.9/python3.9-slim-poetry-sdk.dockerfile \
            ./3.9
          docker push naylscloud/python:3.9-slim-poetry-sdk
  
  python39-slim-poetry-cargo:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Build python3.9-slim-poetry-cargo
        run: |
          docker build \
            -t naylscloud/python:3.9-slim-poetry-cargo \
            -f ./3.9/python3.9-slim-poetry-cargo.dockerfile \
            ./3.9
          docker push naylscloud/python:3.9-slim-poetry-cargo

  python39-slim-poetry-cargo-sdk:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Build python3.9-slim-poetry-cargo-sdk
        run: |
          docker build \
            -t naylscloud/python:3.9-slim-poetry-cargo-sdk \
            -f ./3.9/python3.9-slim-poetry-cargo-sdk.dockerfile \
            ./3.9
          docker push naylscloud/python:3.9-slim-poetry-cargo-sdk
